name: External Pull Request CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read
  packages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-26.04
    environment: external-ci # use this to set up required reviewers
    steps:
      - uses: actions/checkout@v4 # Go get to get-registry-creds/action.yml
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          allow-unsafe-pr-checkout: true
      - name: Fetch Registry Credentials for Fork PR
        id: fork-creds
        uses: ./.github/actions/get-registry-creds
        with:
          auth_service_url: "https://portal.webhare.com/portalapi/ci/get-buildcache-token"
          audience: "https://portal.webhare.com"
      - name: Call CI workflow
        uses: ./.github/workflows/ci.yml
        with:
          ref: ${{ github.event.pull_request.head.sha }}
